kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main

steps:
  - name: Build & Test
    image: node:18.15.0
    commands:
      - cd ./Angular-UI/
      - npm install
      - npm run build
      - npm run test
